# Generated by Django 6.0 on 2026-04-14 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подраздел')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('inf_name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('inf_date', models.DateField(blank=True, null=True, verbose_name='Дата заявки')),
                ('inf_source', models.CharField(blank=True, max_length=100, verbose_name='Источник информации')),
                ('audit_subject', models.CharField(blank=True, max_length=100, verbose_name='Субъект аудита')),
                ('inf_text', models.TextField(blank=True, verbose_name='Информация')),
                ('inf_result', models.CharField(blank=True, max_length=100, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='Подраздел')),
            ],
        ),
    ]
